# Generated by Django 6.0.4 on 2026-05-05 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('minimo', models.IntegerField()),
                ('local', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('BAIXO', 'BAIXO'), ('CRITICO', 'CRITICO')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SAIDA', 'SAIDA')], max_length=20)),
                ('quantidade', models.IntegerField()),
                ('responsavel', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
        ),
    ]
